# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.


notifications:
  email: false

sudo: false

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"

  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

  - "requirements-builder --level=min --extras userprofiles setup.py > .travis-lowest-requirements-with-profiles.txt"
  - "requirements-builder --level=pypi --extras userprofiles setup.py > .travis-release-requirements-with-profiles.txt"
  - "requirements-builder --level=dev --extras userprofiles --req requirements-devel.txt setup.py > .travis-devel-requirements-with-profiles.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[docs,tests]"

script:
  # test without userprofiles
  - "./run-tests.sh"
  # test again with userprofiles
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements-with-profiles.txt"
  - "travis_retry pip install -e .[all]"
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lnielsen
  password:
    secure: "kjJ/h8i/ER5FrMZwmmygl58KKBHhnI+1wIm/+pSkcUwbdZq/MwQXR3CXxhlghxtJ/HQOyLG0MUqhUmSlFTNXr/gDpohcgHzd9b2bdecXQ+heVryXdnJJLObEGNMylYnnywMcZ5z5PEaIHMLse170VsXK5KQIAoViPFg4zo5b9JE5V5LGDAZ0HytsRrVCdGC6vIhHdCRuOO7NPRZj9Nelofwpza9Cpa9roKiK2+spZrPKi/Su0NphsuvwyEGk2i9bnnqUaFridqPhBtthCP6gwJFio0o0Z/682GG90tjoNUbaXzdPlmw39+tOelvEFI2OVYrRNyXEyL73vLqN7ja8SKUU3h+xp4+o/yG6KgrVFQ5whLHIDsfX0Wl4/29XsrsDKLcB0UQUY3Aj4DKmBPScH/HCliGMzkKOk3X4KdzM6jGaDja15Qi5JcCX56lr3o2e3KbGZsG07KL+TpmXE1WjTfs6qHJ1qjWgwBTilalxrOscA2fA6jUtQxU4JlXeYhN4+7PUl4My+pb//f6J5abZ52VanG078r4unjN/zngxZHj8DdfZQhVHWBqWQptK5lqKuXLAOP9acYBzObVNEthQzucdMf/nCnkFe6a+WTsxSpGhnGz+Pffc3fccX85GhCLlv2GuTXbS+bCe7kh+RneVSP57+u73Vuo9Q2vFNgcvt8A="
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
